import type { CheatsheetItem } from "@/lib/types";

export const cheatsheetItems: CheatsheetItem[] = [
  // ====== 命令类 ======
  {
    id: "cmd-dpgen-run",
    category: "command",
    label: "启动 dpgen",
    description: "在项目目录下启动 dpgen 主动学习",
    code: "dpgen run param.json machine.json 2>&1 | tee -a dpgen.log",
    tags: ["dpgen", "启动"],
  },
  {
    id: "cmd-dp-train",
    category: "command",
    label: "DeePMD 训练",
    description: "使用 input.json 训练 DeePMD 模型",
    code: "dp train input.json",
    tags: ["deepmd", "训练"],
  },
  {
    id: "cmd-dp-freeze",
    category: "command",
    label: "冻结模型",
    description: "将 checkpoint 转为 .pb 文件",
    code: "dp freeze -o graph.pb",
    tags: ["deepmd", "模型导出"],
  },
  {
    id: "cmd-lmp-deepmd",
    category: "command",
    label: "LAMMPS + DeePMD",
    description: "使用 DeePMD 势的 LAMMPS 运行",
    code: "lmp -in input.lammps",
    tags: ["lammps", "deepmd"],
  },
  {
    id: "cmd-vasp-run",
    category: "command",
    label: "运行 VASP",
    description: "标准 VASP 运行命令（单节点）",
    code: "mpirun -np $NP /path/to/vasp_std > vasp.out 2>&1",
    tags: ["vasp", "mpi"],
  },
  {
    id: "cmd-qsub",
    category: "command",
    label: "提交 PBS 作业",
    description: "提交作业到超算 batch 队列",
    code: "qsub job.pbs",
    tags: ["pbs", "超算"],
  },
  {
    id: "cmd-qstat",
    category: "command",
    label: "查看作业状态",
    description: "查看当前用户在 PBS 队列中的作业",
    code: "qstat -u student2025",
    tags: ["pbs", "监控"],
  },
  {
    id: "cmd-qdel",
    category: "command",
    label: "删除作业",
    description: "从 PBS 队列中删除指定作业",
    code: "qdel 12345",
    tags: ["pbs", "运维"],
  },
  {
    id: "cmd-tail-log",
    category: "command",
    label: "查看最新日志",
    description: "查看 dpgen 日志最后 20 行",
    code: "tail -20 dpgen.log",
    tags: ["日志", "监控"],
  },
  {
    id: "cmd-grep-error",
    category: "command",
    label: "搜索日志报错",
    description: "在 dpgen 日志中搜索错误关键词",
    code: 'grep -iE "error|exception|killed|oom|segfault|traceback|failed" dpgen.log | tail -20',
    tags: ["日志", "调试"],
  },
  {
    id: "cmd-kill-all",
    category: "command",
    label: "停止所有 dpgen 进程",
    description: "一键杀掉训练+探索+标注",
    code: 'pkill -9 -f "dpgen run"; pkill -9 -f lmp; pkill -9 -f vasp; pkill -9 -f deepmd; pkill -9 -f "dp train"',
    tags: ["进程", "运维"],
  },
  {
    id: "cmd-scp-upload",
    category: "command",
    label: "上传文件到超算",
    description: "用 scp 上传到超算服务器的 dpgen 工作目录",
    code: "scp file student2025@10.157.197.40:/public/home/student2025/zhuangjingrun/dpgen_work/",
    tags: ["scp", "超算", "传输"],
  },
  {
    id: "cmd-conda-activate",
    category: "command",
    label: "激活 conda 环境",
    description: "训练用 deepmd，dpgen 用 deepmd2",
    code: "conda activate deepmd2  # dpgen\nconda activate deepmd   # train",
    tags: ["conda", "环境"],
  },

  // ====== 参数类 ======
  {
    id: "param-trust-lo",
    category: "param",
    label: "model_devi_f_trust_lo",
    description: "力偏差下界（eV/Å），低于此值认为模型准确",
    code: '"model_devi_f_trust_lo": 0.05',
    tags: ["dpgen", "信任度"],
  },
  {
    id: "param-trust-hi",
    category: "param",
    label: "model_devi_f_trust_hi",
    description: "力偏差上界（eV/Å），高于此值触发 VASP 标注",
    code: '"model_devi_f_trust_hi": 0.35',
    tags: ["dpgen", "信任度"],
  },
  {
    id: "param-numb-models",
    category: "param",
    label: "numb_models",
    description: "Committee 模型数量，通常为 4",
    code: '"numb_models": 4',
    tags: ["dpgen", "训练"],
  },
  {
    id: "param-numb-steps",
    category: "param",
    label: "numb_steps",
    description: "每轮训练的总步数",
    code: '"numb_steps": 400000',
    tags: ["deepmd", "训练"],
  },
  {
    id: "param-rcut",
    category: "param",
    label: "rcut / rcut_smth",
    description: "截断半径与平滑截断起点（Å）",
    code: '"rcut": 6.5,\n"rcut_smth": 5.0',
    tags: ["deepmd", "descriptor"],
  },
  {
    id: "param-sel",
    category: "param",
    label: "sel (近邻数)",
    description: "每种元素的截断半径内最大近邻原子数",
    code: '"sel": [40, 40]',
    tags: ["deepmd", "descriptor"],
  },
  {
    id: "param-fp-task-max",
    category: "param",
    label: "fp_task_max / fp_task_min",
    description: "每轮最多/最少 VASP 标注数",
    code: '"fp_task_max": 50,\n"fp_task_min": 1',
    tags: ["dpgen", "fp"],
  },

  // ====== DeePMD 命令类 ======
  {
    id: "cmd-dp-neighbor-stat",
    category: "command",
    label: "dp neighbor-stat 统计近邻",
    description: "统计训练数据中每种原子的最大近邻数，用于确定 sel 参数",
    code: '# PyTorch 后端\ndp --pt neighbor-stat -s data -r 6.0 -t O H\n# 输出 max_nbor_size: [38, 72]\n# 含义：O 最多38个近邻，H 最多72个\n# sel 应设为更高值（如 [46, 92]），留余量给 MD 极端构型',
    tags: ["deepmd", "sel", "neighbor-stat", "近邻统计"],
  },
  {
    id: "cmd-dp-compress",
    category: "command",
    label: "dp compress 模型压缩",
    description: "压缩模型实现 2-4x 推理加速（五阶多项式查表 + 算子合并）",
    code: '# TensorFlow\ndp compress -i graph.pb -o graph-compressed.pb\n\n# PyTorch\ndp --pt compress -i model.pth -o model-compressed.pth\n\n# 压缩后精度损失极小，推荐生产环境使用',
    tags: ["deepmd", "压缩", "加速", "compress"],
  },
  {
    id: "cmd-dp-pretrained",
    category: "command",
    label: "dp pretrained 预训练模型",
    description: "下载官方预训练大模型（DPA-2/DPA-3），可直接用于推理或微调",
    code: '# 下载预训练模型\ndp pretrained download DPA-3.3-1M\ndp pretrained download DPA-3.2-5M\n\n# Python 中直接使用（自动下载）\nfrom deepmd.infer import DeepPot\npot = DeepPot("DPA-3.2-5M")',
    tags: ["deepmd", "预训练", "DPA", "pretrained"],
  },
  {
    id: "cmd-dp-freeze-pt",
    category: "command",
    label: "dp freeze (PyTorch)",
    description: "PyTorch 后端冻结模型，输出 .pth 文件",
    code: '# PyTorch 后端\ndp --pt freeze -o model.pth\n\n# 多任务训练时指定 head\ndp --pt freeze -o model_branch1.pth --head CHOSEN_BRANCH',
    tags: ["deepmd", "freeze", "PyTorch"],
  },
  {
    id: "cmd-dp-test",
    category: "command",
    label: "dp test 模型测试",
    description: "在测试集上评估模型精度（能量/力 RMSE）",
    code: 'dp test -m frozen_model.pb -s test_data/ -n 100\n# 输出：\n# Energy RMSE: 0.0008 eV/atom\n# Force  RMSE: 0.0460 eV/Å\n\n# PyTorch 后端\ndp --pt test -m model.pth -s test_data/',
    tags: ["deepmd", "测试", "RMSE"],
  },
  {
    id: "cmd-dp-restart",
    category: "command",
    label: "dp train 恢复/初始化训练",
    description: "从 checkpoint 恢复训练，或从已有模型初始化",
    code: '# 从 checkpoint 恢复（中断后续跑）\ndp train input.json --restart model.ckpt.pt\n\n# 从已有模型初始化（迁移学习）\ndp train input.json --init-model model.ckpt\n\n# 从冻结模型初始化（调整 sel 等）\ndp train input.json --init-frz-model frozen_model.pb',
    tags: ["deepmd", "恢复", "初始化", "迁移学习"],
  },
  {
    id: "cmd-lcurve-viz",
    category: "command",
    label: "lcurve.out 训练曲线可视化",
    description: "用 matplotlib 可视化 lcurve.out 训练曲线",
    code: 'import numpy as np\nimport matplotlib.pyplot as plt\n\ndata = np.genfromtxt("lcurve.out", names=True)\nfor name in data.dtype.names[1:-1]:\n    plt.plot(data["step"], data[name], label=name)\nplt.legend()\nplt.xlabel("Step")\nplt.ylabel("Loss")\nplt.xscale("symlog")\nplt.yscale("log")\nplt.grid()\nplt.show()',
    tags: ["deepmd", "可视化", "lcurve", "训练曲线"],
  },

  // ====== DeePMD Descriptor 参数 ======
  {
    id: "param-desc-se-e2-a",
    category: "param",
    label: "descriptor: se_e2_a",
    description: "最常用描述符：两体嵌入 + 角度信息（径向+角度），适合大多数体系",
    code: '"descriptor": {\n  "type": "se_e2_a",\n  "rcut": 6.0,        // 截断半径 (Å)\n  "rcut_smth": 0.5,   // 平滑截断起点 (Å)\n  "sel": [46, 92],     // 每种元素最大近邻数\n  "neuron": [25, 50, 100],  // 嵌入网络每层神经元\n  "axis_neuron": 16,   // 轴神经元数（子矩阵维度）\n  "type_one_side": true, // true=仅按邻居类型区分参数\n  "resnet_dt": false,  // ResNet 时间步\n  "seed": 1\n}',
    tags: ["deepmd", "descriptor", "se_e2_a", "参数"],
  },
  {
    id: "param-desc-se-e2-r",
    category: "param",
    label: "descriptor: se_e2_r",
    description: "仅径向描述符：只用距离信息，不含角度，计算更快但精度稍低",
    code: '"descriptor": {\n  "type": "se_e2_r",\n  "rcut": 6.0,\n  "rcut_smth": 0.5,\n  "sel": [46, 92],\n  "neuron": [5, 10, 20],  // 网络比 se_e2_a 小\n  "type_one_side": true,\n  "resnet_dt": false,\n  "seed": 1\n}',
    tags: ["deepmd", "descriptor", "se_e2_r", "参数"],
  },
  {
    id: "param-desc-se-e3",
    category: "param",
    label: "descriptor: se_e3",
    description: "三体嵌入描述符：含键角信息，精度更高但计算量更大",
    code: '"descriptor": {\n  "type": "se_e3",\n  "rcut": 6.0,\n  "rcut_smth": 0.5,\n  "sel": [40, 80],\n  "neuron": [2, 4, 8],  // 三体网络更小\n  "resnet_dt": false,\n  "seed": 1\n}',
    tags: ["deepmd", "descriptor", "se_e3", "参数"],
  },
  {
    id: "param-desc-comparison",
    category: "param",
    label: "描述符选择对比",
    description: "se_e2_a(默认推荐) vs se_e2_r(快速) vs se_e3(高精度) vs hybrid(混合)：精度递增、速度递减",
    code: 'se_e2_a  → 两体嵌入+角度，精度好速度适中（默认选择）\nse_e2_r  → 仅径向，速度快但精度低（大体系快速筛选）\nse_e3    → 三体嵌入+键角，精度最高但最慢（小体系高精度）\nhybrid   → 混合多种 descriptor，可设不同截断半径',
    tags: ["deepmd", "descriptor", "选择", "hybrid"],
  },
  {
    id: "param-desc-hybrid",
    category: "param",
    label: "descriptor: hybrid 混合描述符",
    description: "将多种 descriptor 拼接，可组合不同截断半径和类型",
    code: '"descriptor": {\n  "type": "hybrid",\n  "list": [\n    { "type": "se_e2_a", "rcut": 6.0, ... },\n    { "type": "se_e2_r", "rcut": 8.0, ... }\n  ]\n}',
    tags: ["deepmd", "descriptor", "hybrid", "混合"],
  },
  {
    id: "param-net-size-guide",
    category: "param",
    label: "网络大小调优经验",
    description: "fitting_net 缩小影响小（<5%），embedding_net 缩小影响大（50%+）",
    code: '官方 benchmark (Al₂O₃ 力 RMSE eV/Å):\n\nfitting_net 变化（embedding=[25,50,100]固定）:\n[240,240,240] → 0.040\n[80,80,80]   → 0.040\n[20,20,20]   → 0.041\n[] (线性)    → 0.054\n\nembedding_net 变化（fitting=[240,240,240]固定）:\n[25,50,100]  → 0.040\n[10,20,40]   → 0.047\n[4,8,16]     → 0.073\n[1,2,4]      → 0.097\n\n策略：优先保证 embedding_net 够大',
    tags: ["deepmd", "网络大小", "调优", "benchmark"],
  },
  {
    id: "param-lcurve-columns",
    category: "param",
    label: "lcurve.out 列含义",
    description: "训练曲线文件各列的含义和单位",
    code: '列顺序:\nstep         训练步数\nrmse_val     验证集总损失\nrmse_trn     训练集总损失\nrmse_e_val   验证集能量 RMSE (eV/atom)\nrmse_e_trn   训练集能量 RMSE (eV/atom)\nrmse_f_val   验证集力 RMSE (eV/Å)\nrmse_f_trn   训练集力 RMSE (eV/Å)\nlr           当前学习率\n\n正常: loss 持续下降, val≈trn\n异常: loss 震荡/跳高/不收敛',
    tags: ["deepmd", "lcurve", "训练曲线", "诊断"],
  },

  // ====== DeePMD 训练参数 ======
  {
    id: "param-fitting-net",
    category: "param",
    label: "fitting_net 拟合网络",
    description: "将 descriptor 映射到原子能量的神经网络",
    code: '"fitting_net": {\n  "neuron": [240, 240, 240],  // 每层神经元数\n  "resnet_dt": true,          // ResNet 时间步（推荐 true）\n  "seed": 1,\n  "precision": "float64"      // float64(高精度) 或 float32(混合精度)\n}',
    tags: ["deepmd", "fitting_net", "参数"],
  },
  {
    id: "param-lr-exp",
    category: "param",
    label: "学习率: exp 指数衰减",
    description: "默认学习率策略，lr = start_lr × decay_rate^(step/decay_steps)",
    code: '"learning_rate": {\n  "type": "exp",\n  "start_lr": 0.001,    // 初始学习率\n  "stop_lr": 1e-6,      // 终止学习率\n  "decay_steps": 5000,  // 衰减步数\n  "decay_rate": 0.95,   // 衰减率（可选，自动计算）\n  "smooth": false,      // true=平滑衰减，false=阶梯衰减\n  "warmup_steps": 0     // 预热步数（可选）\n}',
    tags: ["deepmd", "学习率", "exp", "参数"],
  },
  {
    id: "param-lr-cosine",
    category: "param",
    label: "学习率: cosine 余弦退火",
    description: "余弦曲线衰减，通常比指数衰减收敛更平滑",
    code: '"learning_rate": {\n  "type": "cosine",\n  "start_lr": 0.001,\n  "stop_lr": 1e-6,\n  "warmup_steps": 5000  // 预热阶段线性增加\n}',
    tags: ["deepmd", "学习率", "cosine", "参数"],
  },
  {
    id: "param-lr-wsd",
    category: "param",
    label: "学习率: wsd 预热-稳定-衰减",
    description: "大部分时间保持 start_lr，最后 decay_phase_ratio 比例做衰减",
    code: '"learning_rate": {\n  "type": "wsd",\n  "start_lr": 0.001,\n  "stop_lr": 1e-6,\n  "decay_phase_ratio": 0.1,  // 最后10%步数做衰减\n  "decay_type": "inverse_linear"  // 衰减类型：inverse_linear/cosine/linear\n}',
    tags: ["deepmd", "学习率", "wsd", "参数"],
  },
  {
    id: "param-loss-prefactors",
    category: "param",
    label: "loss 损失权重",
    description: "能量/力/virial 损失的权重系数，随学习率线性变化",
    code: '"loss": {\n  "start_pref_e": 0.02,   // 能量损失初始权重\n  "limit_pref_e": 1,      // 能量损失最终权重\n  "start_pref_f": 1000,   // 力损失初始权重（重点学力）\n  "limit_pref_f": 1,      // 力损失最终权重\n  "start_pref_v": 0,      // virial 初始权重（通常为0）\n  "limit_pref_v": 0,      // virial 最终权重\n  "loss_func": "mse",     // mse(L2) 或 mae(L1, 抗异常值)\n  "intensive_ener_virial": false  // true=按N²归一化（多体系推荐）\n}',
    tags: ["deepmd", "loss", "权重", "参数"],
  },
  {
    id: "param-training-section",
    category: "param",
    label: "training 训练配置",
    description: "训练步数、数据、验证、混合精度等核心设置",
    code: '"training": {\n  "training_data": {\n    "systems": ["data0/", "data1/"],  // 训练数据路径\n    "batch_size": "auto",  // auto:N → batch×原子数≥N\n    "auto_prob": "prob_sys_size"  // 按系统大小分配概率\n  },\n  "validation_data": {\n    "systems": ["data_val/"],\n    "batch_size": 1,\n    "numb_btch": 3\n  },\n  "numb_steps": 400000,\n  "seed": 1,\n  "disp_file": "lcurve.out",\n  "disp_freq": 100,\n  "save_freq": 1000,\n  "mixed_precision": {  // 可选：混合精度训练\n    "output_prec": "float32",\n    "compute_prec": "float16"\n  }\n}',
    tags: ["deepmd", "training", "batch_size", "参数"],
  },
  {
    id: "param-optimizer",
    category: "param",
    label: "optimizer 优化器",
    description: "训练优化器选择：Adam(默认), AdamW, LKF, AdaMuon(仅PyTorch)",
    code: '"optimizer": {\n  "type": "Adam",      // TF: 仅Adam; PT: Adam/AdamW/LKF/AdaMuon\n  "adam_beta1": 0.9,   // Adam 一阶矩衰减率\n  "adam_beta2": 0.999, // Adam 二阶矩衰减率\n  "weight_decay": 0     // L2 正则化权重（AdamW 解耦）\n}',
    tags: ["deepmd", "optimizer", "Adam", "参数"],
  },

  // ====== DP-GEN 探索参数 ======
  {
    id: "param-model-devi-jobs",
    category: "param",
    label: "model_devi_jobs 探索任务",
    description: "DP-GEN MD 探索配置：温度、压力、步长、系综",
    code: '"model_devi_jobs": [{\n  "sys_idx": [0],       // 使用第0组初始结构\n  "temps": [300, 600, 1000],  // 温度列表 (K)\n  "press": [1.0],       // 压力列表 (bar)\n  "trj_freq": 10,       // 每10步保存一帧\n  "nsteps": 3000,       // MD 总步数\n  "ensemble": "nvt",    // 系综: nvt/npt/nve\n  "_idx": "00"          // 迭代编号\n}]',
    tags: ["dpgen", "model_devi", "MD", "探索"],
  },
  {
    id: "param-model-devi-dt",
    category: "param",
    label: "model_devi_dt / model_devi_skip",
    description: "MD 时间步长(ps)和跳过帧数（每隔skip帧保存）",
    code: '"model_devi_dt": 0.002,    // 时间步长 0.002 ps = 2 fs\n"model_devi_skip": 0,      // 跳过前N帧（0=全部保存）\n"model_devi_clean_traj": true  // 清理轨迹文件节省空间',
    tags: ["dpgen", "model_devi", "时间步"],
  },

  // ====== 路径类 ======
  {
    id: "path-local-dp-train",
    category: "path",
    label: "dp (训练)",
    description: "deepmd 环境中的 dp 可执行文件",
    code: "/home/kobe/miniconda3/envs/deepmd/bin/dp",
    tags: ["deepmd", "本地路径"],
  },
  {
    id: "path-local-dpgen",
    category: "path",
    label: "dpgen",
    description: "deepmd2 环境中的 dpgen 可执行文件",
    code: "/home/kobe/miniconda3/envs/deepmd2/bin/dpgen",
    tags: ["dpgen", "本地路径"],
  },
  {
    id: "path-local-lmp",
    category: "path",
    label: "lmp (DeePMD版)",
    description: "deepmd 环境中的 LAMMPS",
    code: "/home/kobe/miniconda3/envs/deepmd/bin/lmp",
    tags: ["lammps", "本地路径"],
  },
  {
    id: "path-hpc-vasp",
    category: "path",
    label: "vasp_std (超算)",
    description: "超算上的 VASP 可执行文件",
    code: "/public/software/vasp.5.4.4/bin/vasp_std",
    tags: ["vasp", "超算路径"],
  },
  {
    id: "path-hpc-intel",
    category: "path",
    label: "Intel 环境 (超算)",
    description: "超算 Intel 编译环境初始化脚本",
    code: "source /public/software/intel2020u2/intel2020u2_env.sh",
    tags: ["超算路径", "环境"],
  },
  {
    id: "path-hpc-work",
    category: "path",
    label: "dpgen 工作目录 (超算)",
    description: "超算上 dpgen 的 remote_root",
    code: "/public/home/student2025/zhuangjingrun/dpgen_work/",
    tags: ["dpgen", "超算路径"],
  },
  {
    id: "path-local-project",
    category: "path",
    label: "项目根目录",
    description: "TiC MLP 项目的本地根目录",
    code: "~/vasp_run/TiC_MLP/",
    tags: ["项目", "本地路径"],
  },

  // ====== 脚本类 ======
  {
    id: "script-clean-startup",
    category: "script",
    label: "干净环境启动",
    description: "避免 conda 污染 VASP 动态库的启动脚本",
    code: `#!/bin/bash
source /home/kobe/miniconda3/etc/profile.d/conda.sh
conda activate dpgen_test_env
unset LD_LIBRARY_PATH
export PATH=/home/kobe/miniconda3/envs/dpgen_test_env/bin:/usr/local/bin:/usr/bin:/bin
dpgen run param.json machine.json`,
    tags: ["启动", "脚本", "环境"],
  },
  {
    id: "script-watch-dpgen",
    category: "script",
    label: "dpgen 监控脚本",
    description: "每30秒检查进程存活+报错扫描+进度显示",
    code: `#!/bin/bash
while true; do
  pgrep -f "dpgen run" > /dev/null && echo "✅ running" || echo "❌ dead"
  tail -100 dpgen.log | grep -iE "error|failed" | tail -5
  sleep 30
done`,
    tags: ["监控", "脚本", "dpgen"],
  },

  // ====== Slurm 命令 ======
  {
    id: "cmd-sbatch",
    category: "command",
    label: "提交 Slurm 作业",
    description: "用 sbatch 提交作业到 Slurm 集群",
    code: "sbatch job.slurm",
    tags: ["slurm", "超算", "提交"],
  },
  {
    id: "cmd-squeue",
    category: "command",
    label: "查看 Slurm 作业",
    description: "查看当前用户的 Slurm 作业状态",
    code: "squeue -u $USER",
    tags: ["slurm", "监控"],
  },
  {
    id: "cmd-scancel",
    category: "command",
    label: "取消 Slurm 作业",
    description: "取消指定的 Slurm 作业",
    code: "scancel 12345",
    tags: ["slurm", "运维"],
  },
  {
    id: "param-machine-json-batch",
    category: "param",
    label: "machine.json batch_type",
    description: "DP-GEN 任务批处理类型：PBS/Slurm/LSF/Shell",
    code: '"batch_type": "Slurm"  # Slurm 集群\n"batch_type": "PBS"     # PBS/Torque 集群\n"batch_type": "Shell"   # 本地直接执行',
    tags: ["dpgen", "machine.json", "slurm", "pbs"],
  },

  // ====== dpdata / 数据处理 ======
  {
    id: "cmd-dpdata-read-outcar",
    category: "command",
    label: "dpdata 读取 OUTCAR",
    description: "用 dpdata 从 VASP OUTCAR 提取训练数据",
    code: 'import dpdata\ns = dpdata.LabeledSystem("OUTCAR", fmt="vasp/outcar")\nprint(f"帧数: {len(s)}, 原子数: {s.get_natoms()}")',
    tags: ["dpdata", "VASP", "数据转换"],
  },
  {
    id: "cmd-dpdata-export-npy",
    category: "command",
    label: "dpdata 导出 DeePMD 格式",
    description: "将 LabeledSystem 导出为 DeePMD numpy 训练格式",
    code: 's.to_deepmd_npy("training_data/")\n# 生成 set.000/ 目录：box.npy, coord.npy, energy.npy, force.npy, virial.npy',
    tags: ["dpdata", "deepmd", "数据转换"],
  },
  {
    id: "cmd-dpdata-merge",
    category: "command",
    label: "dpdata 合并多个系统",
    description: "合并多个 OUTCAR 的数据（DP-GEN 数据回流核心操作）",
    code: 'merged = dpdata.LabeledSystem("OUTCAR_1")\nfor f in ["OUTCAR_2", "OUTCAR_3"]:\n    merged.append(dpdata.LabeledSystem(f))\nmerged.to_deepmd_npy("merged_data/")',
    tags: ["dpdata", "合并", "数据回流"],
  },
  {
    id: "cmd-dpdata-vasprun",
    category: "command",
    label: "dpdata 读取 vasprun.xml",
    description: "从 vasprun.xml 读取（比 OUTCAR 更稳定）",
    code: 's = dpdata.LabeledSystem("vasprun.xml", fmt="vasp/xml")',
    tags: ["dpdata", "VASP", "xml"],
  },
  {
    id: "cmd-dpdata-subsystem",
    category: "command",
    label: "dpdata 切分数据",
    description: "按索引切分子集（训练/测试分离）",
    code: 'import numpy as np\nidx = np.random.permutation(len(s))[:80]\ntrain = s.sub_system(idx)\ntrain.to_deepmd_npy("train/")',
    tags: ["dpdata", "切分", "训练集"],
  },
  {
    id: "cmd-dpdata-batch-collect",
    category: "command",
    label: "批量收集 FP OUTCAR",
    description: "DP-GEN 一轮迭代后批量收集标注数据",
    code: 'from pathlib import Path\nsystems = []\nfor d in sorted(Path("iter.000000/02.fp").glob("task.*")):\n    if (d/"OUTCAR").exists():\n        systems.append(dpdata.LabeledSystem(str(d/"OUTCAR")))\nm = systems[0]\nfor s in systems[1:]: m.append(s)\nm.to_deepmd_npy("new_data/")',
    tags: ["dpdata", "dpgen", "批量", "数据回流"],
  },
  {
    id: "param-dpdata-formats",
    category: "param",
    label: "dpdata 支持格式全表",
    description: "dpdata 支持的所有输入/输出格式（25+种）",
    code: '读取格式 (fmt 参数):\nvasp/outcar    VASP OUTCAR\nvasp/xml       VASP vasprun.xml\nvasp/poscar    VASP POSCAR\ndeepmd/npy     DeePMD numpy\ndeepmd/raw     DeePMD 文本\ngaussian/log   Gaussian 日志\ncp2k/output    CP2K 输出\nqe/pw/scf      Quantum ESPRESSO\nlammps/dump    LAMMPS dump\nlammps/data    LAMMPS data\nfhi_aims/output FHI-aims\nsiesta/output  SIESTA\nabacus/md      ABACUS\nquip/gap/xyz   QUIP/GAP\nxyz            通用 XYZ\n\n导出方法:\n.to_deepmd_npy() .to_deepmd_raw()\n.to_vasp_poscar() .to_lammps_lmp()',
    tags: ["dpdata", "格式", "API"],
  },
  {
    id: "cmd-dpdata-quality-check",
    category: "command",
    label: "dpdata 数据质量检查",
    description: "检查训练数据的力/能量分布，排除异常帧",
    code: 'import numpy as np\nforces = system.data["forces"]  # (n_frames, n_atoms, 3)\nforce_max = np.abs(forces).max(axis=(1,2))\nbad = np.where(force_max > 50)[0]  # 力>50 eV/Å为异常\nprint(f"异常帧: {len(bad)}/{len(system)}")\nif len(bad): print(f"索引: {bad.tolist()}")',
    tags: ["dpdata", "质量检查", "异常值"],
  },
  {
    id: "cmd-dpdata-energy-shift",
    category: "command",
    label: "dpdata 能量参考对齐",
    description: "不同 DFT 计算的能量参考不一致时，需要对齐能量零点",
    code: 'import numpy as np\n# 计算每原子平均能量作为参考\ne_per_atom = system.data["energies"] / system.get_natoms()\nref_e = np.mean(e_per_atom)  # 或用已知参考值\n# 手动偏移（dpdata 暂无内置方法）\nsystem.data["energies"] -= shift_value',
    tags: ["dpdata", "能量对齐", "参考"],
  },

  // ====== OVITO / 可视化 ======
  {
    id: "cmd-ovito-python",
    category: "command",
    label: "OVITO Python 管线",
    description: "导入 LAMMPS dump 并进行 PTM 结构分析",
    code: "from ovito.io import import_file\nfrom ovito.modifiers import PolyhedralTemplateMatchingModifier\n\npipeline = import_file('dump.lammpstrj')\npipeline.modifiers.append(PolyhedralTemplateMatchingModifier())",
    tags: ["ovito", "python", "PTM"],
  },
  {
    id: "cmd-ovito-dxa",
    category: "command",
    label: "DXA 位错分析",
    description: "Python 脚本做位错提取与密度统计",
    code: "from ovito.modifiers import DislocationAnalysisModifier\n\npipeline.modifiers.append(DislocationAnalysisModifier())\ndata = pipeline.compute()\nL = data.attributes['DislocationAnalysis.total_line_length']\nV = data.attributes['DislocationAnalysis.cell_volume']\nprint(f'Dislocation density: {L/V:.3e} A^-2')",
    tags: ["ovito", "DXA", "位错"],
  },
  {
    id: "cmd-ovito-tachyon",
    category: "command",
    label: "Tachyon 高质量渲染",
    description: "使用 OVITO Tachyon 渲染发表级图像",
    code: "from ovito.vis import Viewport, TachyonRenderer\n\nvp = Viewport(type=Viewport.Type.Perspective)\nvp.render_image(size=(1920,1080), filename='render.png',\n  renderer=TachyonRenderer(ambient_occlusion=True, shadows=True))",
    tags: ["ovito", "渲染", "Tachyon"],
  },

  // ====== ASE / 结构操作 ======
  {
    id: "cmd-ase-build",
    category: "command",
    label: "ASE 构建超胞/表面",
    description: "用 ASE 创建晶体结构、切表面、做超胞",
    code: "from ase.build import bulk, fcc111, make_supercell\n\ncu = bulk('Cu', 'fcc', a=3.61)\ncu_sc = cu * (3, 3, 3)  # 超胞\ncu111 = fcc111('Cu', a=3.61, size=(2,2,4), vacuum=10.0)  # 表面",
    tags: ["ase", "结构", "表面"],
  },
  {
    id: "cmd-ase-relax",
    category: "command",
    label: "ASE 结构弛豫",
    description: "对接 VASP/GPAW 做 BFGS 弛豫",
    code: "from ase.optimize import BFGS\nfrom ase.calculators.vasp import Vasp\n\natoms.calc = Vasp(xc='PBE', encut=500, kpts=(4,4,1), directory='relax')\nopt = BFGS(atoms)\nopt.run(fmax=0.02)  # eV/A",
    tags: ["ase", "弛豫", "DFT"],
  },

  // ====== LAMMPS / MD ======
  {
    id: "cmd-lmp-npt",
    category: "command",
    label: "LAMMPS NPT 分子动力学",
    description: "等温等压系综 MD 运行（含弛豫）",
    code: "units metal\ntimestep 0.001\nvelocity all create 300 12345\nfix npt all npt temp 300 300 0.1 iso 0 0 1.0\nrun 100000",
    tags: ["lammps", "NPT", "MD"],
  },
  {
    id: "cmd-lmp-minimize",
    category: "command",
    label: "LAMMPS 能量最小化",
    description: "MD 前先做能量最小化消除坏接触",
    code: "minimize 1.0e-10 1.0e-10 10000 100000",
    tags: ["lammps", "最小化", "MD"],
  },

  // ====== DFT 收敛参数 ======
  {
    id: "param-encut-convergence",
    category: "param",
    label: "ENCUT 截断能",
    description: "PBE 泛函推荐 ENCUT = 1.3 × max(ENMAX)，弹性常数建议 1.5×",
    code: 'ENCUT = 500  # 1.3 × ENMAX\n# 收敛测试: for ENCUT in 300 400 500 600',
    tags: ["dft", "encut", "收敛"],
  },
  {
    id: "param-kpoint-density",
    category: "param",
    label: "K 点密度",
    description: "k_i × a_i ≈ 30-40 Å 为精确计算，能带用高对称路径，DOS 加密 2-3×",
    code: "# vaspkit -task 102 生成 KPOINTS\n# 输入密度 ~0.04 (精确) 或 ~0.03 (DOS)",
    tags: ["dft", "kpoints", "收敛"],
  },
  {
    id: "param-smearing",
    category: "param",
    label: "ISMEAR / SIGMA",
    description: "半导体 ISMEAR=0, SIGMA=0.05；金属 ISMEAR=1；能带/DOS 用 ISMEAR=-5 (四面体)",
    code: "ISMEAR = 0    # 半导体: Gaussian\nSIGMA = 0.05\nISMEAR = 1    # 金属: Methfessel-Paxton\nISMEAR = -5   # DOS/能带: 四面体方法",
    tags: ["dft", "smearing", "VASP"],
  },
];
